---
- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
- name: install useful tools
  apt: name={{item}} state=present
  with_items:
    - vim
    - tmux
    - curl
    - wget
    - git
    - net-tools
    - htop
    - fish
    - make
    - sysbench
    - sudo
    - mesa-utils
    # - blueman