---
- name: install useful tools
  apt: name={{item}} state=present
  with_items:
    - vim
    - tmux
    - curl
    - wget
    - git
    - net-tools
    - htop
    - fish
    - make
    - sysbench
    - sudo
    - mesa-utils
    # - blueman